### ISSUE TITLE
Ready for release

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion-module-iiyama-prolite#1]
@josephdadams - Ready and tested. I'd be grateful if this could go into the beta

**Comment by josephdadams** [comment]
Your help file needs fixing. It references another module and is otherwise blank.

**Comment by BryanCrotaz** [comment]
Whoops!!


Fixed.

**Comment by josephdadams** [comment]
@Julusian can you review this before we put it in? I'm not in a position to review ts based modules

**Comment by Julusian** [comment]
Please move typescript to be a devDependency. You should also make the version of the dependency match the one used in the build script https://github.com/bitfocus/companion-module-iiyama-prolite/blob/main/package.json#L28, otherwise it is likely to produce type errors as you could end up accidentally using syntax only supported in one of them

Im personally not a fan of side effects in property setters https://github.com/bitfocus/companion-module-iiyama-prolite/blob/main/src/index.ts#L32. I find it makes it hard to know what will happen from a glance. Up to you whether to change that.

https://github.com/bitfocus/companion-module-iiyama-prolite/blob/main/src/index.ts#L269 we make no guarantees that subscribe and unsubscribe will be called the same number of times. It is very possible that we will call subscribe multiple times without calling unsubscribe in the middle. Which will cause this logic to leak references. I recommend making videoSubscriptions be a `Set<string>` of the feedback id. That way multiple calls to subscribe will not end up duplicating the counts.

https://github.com/bitfocus/companion-module-iiyama-prolite/blob/main/src/prolite-api/protocol.ts might be worth assigning the enum entries concrete values, to make it harder to break if someone does add something wrong?

https://github.com/bitfocus/companion-module-iiyama-prolite/blob/main/src/prolite-api/protocols/LH42UHS.ts#L58 Why are these 'ts-ignore'? I dont see why they need to be.

**Comment by BryanCrotaz** [comment]
Fabulous useful review - thanks. I've fixed all these issues.

**Comment by Julusian** [comment]
This will be in the next beta build

**Comment by BryanCrotaz** [comment]
@Julusian @josephdadams  I think this is ready now

**Comment by BryanCrotaz** [comment]
It's not in the build yet. Please could you update it?
